# Generated by Django 5.2.16 on 2026-08-06 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "运行中"),
                            ("SUCCESS", "成功"),
                            ("FAILURE", "失败"),
                            ("WAIT_USER", "等待用户输入"),
                            ("INTERRUPTED", "被打断"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("node_graph", models.JSONField(default=dict)),
                ("progress", models.JSONField(default=dict)),
                ("context", models.JSONField(default=dict)),
                ("token_usage", models.JSONField(default=dict)),
                ("details", models.JSONField(default=dict)),
                ("is_interrupted", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_executions",
                        to="application.application",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_executions",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_execution",
            },
        ),
    ]
