# Generated by Django 5.2.16 on 2026-08-06 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("desc", models.CharField(blank=True, default="", max_length=512)),
                ("code", models.TextField(default="")),
                ("input_schema", models.JSONField(default=dict)),
                ("is_builtin", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PUBLISHED", "已发布"),
                            ("DISABLED", "已禁用"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tool",
            },
        ),
        migrations.CreateModel(
            name="ToolRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chat_id", models.UUIDField(blank=True, null=True)),
                ("inputs", models.JSONField(default=dict)),
                ("output", models.JSONField(blank=True, default=dict, null=True)),
                ("stdout", models.TextField(blank=True, default="")),
                ("stderr", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "成功"),
                            ("FAILURE", "失败"),
                            ("REJECTED", "被沙箱拒绝"),
                            ("TIMEOUT", "超时"),
                        ],
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                ("run_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="tool.tool",
                    ),
                ),
            ],
            options={
                "db_table": "tool_record",
                "indexes": [
                    models.Index(
                        fields=["tool", "-created_at"],
                        name="tool_record_tool_id_de0557_idx",
                    )
                ],
            },
        ),
    ]
