# Generated by Django 5.2.16 on 2026-08-05 23:52

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "embedding_model_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "vector_type",
                    models.CharField(
                        choices=[
                            ("vector", "向量检索"),
                            ("supported", "仅全文检索（不支持向量）"),
                        ],
                        default="vector",
                        max_length=32,
                    ),
                ),
                (
                    "index_name",
                    models.CharField(default="maxkb_embedding", max_length=128),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("base", "基础知识库"), ("web", "Web 知识库")],
                        default="base",
                        max_length=32,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledges",
                        to="identity.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge",
                "ordering": ["-update_time"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="knowledge.knowledge",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="knowledge.knowledgefolder",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_folder",
            },
        ),
        migrations.AddField(
            model_name="knowledge",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledges",
                to="knowledge.knowledgefolder",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("base", "基础文档"),
                            ("qa", "QA 文档"),
                            ("web", "WEB文档"),
                        ],
                        default="base",
                        max_length=32,
                    ),
                ),
                ("char_length", models.IntegerField(default=0)),
                ("para_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("STARTED", "处理中"),
                            ("SUCCESS", "成功"),
                            ("FAILURE", "失败"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="knowledge.knowledge",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="knowledge.knowledgefolder",
                    ),
                ),
            ],
            options={
                "db_table": "document",
                "ordering": ["-update_time"],
            },
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="", max_length=256)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("STARTED", "处理中"),
                            ("SUCCESS", "成功"),
                            ("FAILURE", "失败"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("version", models.IntegerField(default=1)),
                ("compare_content_hash", models.CharField(default="", max_length=64)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="knowledge.document",
                    ),
                ),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="knowledge.knowledge",
                    ),
                ),
            ],
            options={
                "db_table": "paragraph",
                "ordering": ["create_time"],
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "index_name",
                    models.CharField(default="maxkb_embedding", max_length=128),
                ),
                ("vector", pgvector.django.vector.VectorField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge.document",
                    ),
                ),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge.knowledge",
                    ),
                ),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge.paragraph",
                    ),
                ),
            ],
            options={
                "db_table": "embedding",
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="knowledge.paragraph",
                    ),
                ),
            ],
            options={
                "db_table": "problem",
            },
        ),
        migrations.CreateModel(
            name="Termbase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termbases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termbases",
                        to="identity.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "termbase",
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "termbase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="knowledge.termbase",
                    ),
                ),
            ],
            options={
                "db_table": "term",
            },
        ),
        migrations.CreateModel(
            name="DocumentTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("split", "切分"),
                            ("embed", "向量化"),
                            ("tokenize", "全文分词"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("STARTED", "处理中"),
                            ("SUCCESS", "成功"),
                            ("FAILURE", "失败"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("queue", models.CharField(default="celery", max_length=32)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("complete_time", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_task",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "type"), name="uniq_doc_task_type"
                    )
                ],
            },
        ),
    ]
