# Generated by Django 5.2.16 on 2026-08-06 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("desc", models.TextField(blank=True, default="")),
                (
                    "app_type",
                    models.CharField(
                        choices=[("SIMPLE", "简单问答")],
                        default="SIMPLE",
                        max_length=16,
                    ),
                ),
                (
                    "access_token",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("model_setting", models.JSONField(default=dict)),
                ("knowledge_setting", models.JSONField(default=dict)),
                ("max_access_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("workspace_id", models.CharField(default="default", max_length=64)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "application",
            },
        ),
    ]
