# Generated by Django 5.2.16 on 2026-08-06 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="work_flow",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="application",
            name="app_type",
            field=models.CharField(
                choices=[("SIMPLE", "简单问答"), ("WORK_FLOW", "工作流")],
                default="SIMPLE",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("work_flow_snapshot", models.JSONField(default=dict)),
                ("is_published", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="application.application",
                    ),
                ),
            ],
            options={
                "db_table": "application_version",
            },
        ),
    ]
