# Generated by Django 5.2.16 on 2026-08-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0002_application_work_flow_alter_application_app_type_and_more",
        ),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="api_key",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application",
                to="identity.apikey",
            ),
        ),
    ]
