# Generated by Django 5.2.16 on 2026-08-06 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("timer", "定时触发"), ("webhook", "Webhook 触发")],
                        default="timer",
                        max_length=16,
                    ),
                ),
                ("setting", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trigger",
            },
        ),
        migrations.CreateModel(
            name="TriggerTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("application", "执行应用"), ("tool", "执行工具")],
                        max_length=16,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("task_args", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="trigger.trigger",
                    ),
                ),
            ],
            options={
                "db_table": "trigger_task",
            },
        ),
        migrations.CreateModel(
            name="TaskRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待执行"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "执行成功"),
                            ("FAILURE", "执行失败"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("execute_result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="trigger.trigger",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="trigger.triggertask",
                    ),
                ),
            ],
            options={
                "db_table": "task_record",
                "indexes": [
                    models.Index(
                        fields=["trigger", "-create_time"],
                        name="task_record_trigger_94be13_idx",
                    )
                ],
            },
        ),
    ]
