# Generated by Django 5.2.16 on 2026-08-04 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("provider", models.CharField(db_index=True, max_length=64)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("LLM", "Llm"),
                            ("EMBEDDING", "Embedding"),
                            ("STT", "Stt"),
                            ("TTS", "Tts"),
                            ("IMAGE", "Image"),
                            ("TTI", "Tti"),
                            ("RERANKER", "Reranker"),
                            ("TTV", "Ttv"),
                            ("ITV", "Itv"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(max_length=128)),
                ("credential", models.TextField()),
                ("model_params", models.JSONField(default=dict)),
                ("is_cacheable", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("ERROR", "凭据错误"),
                            ("DOWNLOAD", "下载中"),
                        ],
                        default="SUCCESS",
                        max_length=16,
                    ),
                ),
                ("workspace_id", models.CharField(default="default", max_length=64)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "model",
                "unique_together": {
                    ("provider", "model_type", "model_name", "workspace_id")
                },
            },
        ),
    ]
