# Generated by Django 5.2.16 on 2026-08-06 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("chat_type", models.CharField(default="AUDIENCE", max_length=16)),
                ("name", models.CharField(blank=True, default="", max_length=256)),
                ("abstract", models.TextField(blank=True, default="")),
                (
                    "current_chat_record_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("delete_time", models.DateTimeField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="application.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat",
            },
        ),
        migrations.CreateModel(
            name="ChatRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("answer_text_list", models.JSONField(default=list)),
                ("answer", models.TextField(blank=True, default="")),
                ("reasoning_content", models.TextField(blank=True, default="")),
                ("tokens", models.JSONField(default=dict)),
                ("details", models.JSONField(default=dict)),
                ("source", models.JSONField(default=list)),
                (
                    "vote_status",
                    models.CharField(
                        choices=[
                            ("UN_VOTE", "未投票"),
                            ("LIKE", "点赞"),
                            ("UNLIKE", "点踩"),
                        ],
                        default="UN_VOTE",
                        max_length=16,
                    ),
                ),
                ("vote_reason", models.TextField(blank=True, default="")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "db_table": "chat_record",
            },
        ),
    ]
